version: '3.8'

services:
  api:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - PORT=3001
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=assistantmj
    volumes:
      - .:/app
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: assistantmj
    ports:
      - "5432:5432"
